Repository BAMBOO-Hompage/bamboo-server, pull requests merged in 2025-01, with the labels that each got.

#8 Feat/6 cicd update
  .github/workflows/dev_deploy.yml
Labels: feature

#10 🐛 불필요한 테스트 삭제
  src/test/java/SMU/BAMBOO/Hompage/BambooHompageApplicationTests.java
Labels: fix

#13 ✨ Entity 구현
  src/main/java/SMU/BAMBOO/Hompage/domain/award/entity/Award.java
  src/main/java/SMU/BAMBOO/Hompage/domain/enums/KnowledgeType.java
  src/main/java/SMU/BAMBOO/Hompage/domain/enums/NoticeType.java
  src/main/java/SMU/BAMBOO/Hompage/domain/enums/Role.java
  src/main/java/SMU/BAMBOO/Hompage/domain/enums/SubjectName.java
  src/main/java/SMU/BAMBOO/Hompage/domain/inventory/entity/Inventory.java
  src/main/java/SMU/BAMBOO/Hompage/domain/knowledge/entity/Knowledge.java
  src/main/java/SMU/BAMBOO/Hompage/domain/knowledgeComment/entity/KnowledgeComment.java
  src/main/java/SMU/BAMBOO/Hompage/domain/libraryPost/entity/LibraryPost.java
  src/main/java/SMU/BAMBOO/Hompage/domain/mainActivites/entity/MainActivities.java
  src/main/java/SMU/BAMBOO/Hompage/domain/mapping/LibraryPostTag.java
  src/main/java/SMU/BAMBOO/Hompage/domain/mapping/MemberStudy.java
  src/main/java/SMU/BAMBOO/Hompage/domain/member/entity/Member.java
  src/main/java/SMU/BAMBOO/Hompage/domain/notice/entity/Notice.java
  src/main/java/SMU/BAMBOO/Hompage/domain/noticeComment/entity/NoticeComment.java
  src/main/java/SMU/BAMBOO/Hompage/domain/study/entity/Study.java
  src/main/java/SMU/BAMBOO/Hompage/domain/subject/entity/Subject.java
  src/main/java/SMU/BAMBOO/Hompage/domain/tag/entity/Tag.java
  src/main/java/SMU/BAMBOO/Hompage/domain/weeklyContent/entity/WeeklyContent.java
  src/main/java/SMU/BAMBOO/Hompage/global/common/BaseEntity.java
  src/main/resources/application.properties
  src/main/resources/application.yml
Labels: feature

#17 ✨ JWT 기반 회원가입, 로그인 구현
  build.gradle
  src/main/java/SMU/BAMBOO/Hompage/TestController.java
  src/main/java/SMU/BAMBOO/Hompage/domain/enums/Role.java
  src/main/java/SMU/BAMBOO/Hompage/domain/member/controller/MemberController.java
  src/main/java/SMU/BAMBOO/Hompage/domain/member/dto/request/MemberLoginDto.java
  src/main/java/SMU/BAMBOO/Hompage/domain/member/dto/request/MemberSignUpDto.java
  src/main/java/SMU/BAMBOO/Hompage/domain/member/dto/response/LoginResponse.java
  src/main/java/SMU/BAMBOO/Hompage/domain/member/dto/response/MemberResponse.java
  src/main/java/SMU/BAMBOO/Hompage/domain/member/entity/Member.java
  src/main/java/SMU/BAMBOO/Hompage/domain/member/repository/MemberJpaRepository.java
  src/main/java/SMU/BAMBOO/Hompage/domain/member/repository/MemberRepository.java
  src/main/java/SMU/BAMBOO/Hompage/domain/member/repository/MemberRepositoryImpl.java
  src/main/java/SMU/BAMBOO/Hompage/domain/member/service/MemberService.java
  src/main/java/SMU/BAMBOO/Hompage/domain/member/service/MemberServiceImpl.java
  src/main/java/SMU/BAMBOO/Hompage/global/config/RedisConfig.java
  src/main/java/SMU/BAMBOO/Hompage/global/config/SecurityConfig.java
  src/main/java/SMU/BAMBOO/Hompage/global/exception/CustomAuthenticationEntryPoint.java
  src/main/java/SMU/BAMBOO/Hompage/global/exception/ErrorCode.java
  src/main/java/SMU/BAMBOO/Hompage/global/jwt/Token.java
  src/main/java/SMU/BAMBOO/Hompage/global/jwt/controller/AuthController.java
  src/main/java/SMU/BAMBOO/Hompage/global/jwt/filter/JwtAuthenticationFilter.java
  src/main/java/SMU/BAMBOO/Hompage/global/jwt/repository/TokenRepository.java
  src/main/java/SMU/BAMBOO/Hompage/global/jwt/service/AuthService.java
  src/main/java/SMU/BAMBOO/Hompage/global/jwt/userDetails/CustomUserDetails.java
  src/main/java/SMU/BAMBOO/Hompage/global/jwt/userDetails/CustomUserDetailsService.java
  src/main/java/SMU/BAMBOO/Hompage/global/jwt/util/JwtUtil.java
  src/main/resources/application.yml
Labels: feature

#18 15 email auth
  build.gradle
  src/main/java/SMU/BAMBOO/Hompage/domain/member/controller/MemberController.java
  src/main/java/SMU/BAMBOO/Hompage/domain/member/repository/MemberJpaRepository.java
  src/main/java/SMU/BAMBOO/Hompage/domain/member/repository/MemberRepository.java
  src/main/java/SMU/BAMBOO/Hompage/domain/member/repository/MemberRepositoryImpl.java
  src/main/java/SMU/BAMBOO/Hompage/domain/member/service/MemberServiceImpl.java
  src/main/java/SMU/BAMBOO/Hompage/global/config/AsyncConfig.java
  src/main/java/SMU/BAMBOO/Hompage/global/config/RedisConfig.java
  src/main/java/SMU/BAMBOO/Hompage/global/config/SecurityConfig.java
  src/main/java/SMU/BAMBOO/Hompage/global/exception/ErrorCode.java
  src/main/java/SMU/BAMBOO/Hompage/global/mail/config/MailConfig.java
  src/main/java/SMU/BAMBOO/Hompage/global/mail/controller/MailController.java
  src/main/java/SMU/BAMBOO/Hompage/global/mail/dto/request/VerifyEmailDto.java
  src/main/java/SMU/BAMBOO/Hompage/global/mail/dto/response/EmailVerificationResponse.java
  src/main/java/SMU/BAMBOO/Hompage/global/mail/service/MailService.java
  src/main/java/SMU/BAMBOO/Hompage/global/redis/config/RedisConfig.java
  src/main/java/SMU/BAMBOO/Hompage/global/redis/service/RedisService.java
  src/main/resources/application.yml
  src/main/resources/templates/verification-email.html
Labels: feature

#23 ✨ 스웨거 추가 설정 및 CurrentMember 어노테이션 추가
  src/main/java/SMU/BAMBOO/Hompage/domain/member/annotation/CurrentMember.java
  src/main/java/SMU/BAMBOO/Hompage/domain/member/annotation/resolver/AuthenticatedMemberResolver.java
  src/main/java/SMU/BAMBOO/Hompage/domain/member/controller/MemberController.java
  src/main/java/SMU/BAMBOO/Hompage/domain/member/service/MemberService.java
  src/main/java/SMU/BAMBOO/Hompage/domain/member/service/MemberServiceImpl.java
  src/main/java/SMU/BAMBOO/Hompage/global/config/SwaggerConfig.java
  src/main/java/SMU/BAMBOO/Hompage/global/config/WebConfig.java
  src/main/java/SMU/BAMBOO/Hompage/global/jwt/filter/JwtAuthenticationFilter.java
  src/main/java/SMU/BAMBOO/Hompage/global/jwt/service/AuthService.java
  src/main/java/SMU/BAMBOO/Hompage/global/jwt/util/JwtUtil.java
Labels: feature, refactor

#24 ✨ 로그아웃 기능
  src/main/java/SMU/BAMBOO/Hompage/domain/member/controller/MemberController.java
  src/main/java/SMU/BAMBOO/Hompage/domain/member/service/MemberService.java
  src/main/java/SMU/BAMBOO/Hompage/domain/member/service/MemberServiceImpl.java
  src/main/java/SMU/BAMBOO/Hompage/global/exception/ErrorCode.java
  src/main/java/SMU/BAMBOO/Hompage/global/jwt/util/JwtUtil.java
Labels: feature

#21 ✨ 주요활동 게시판 CRUD 구현
  .github/workflows/dev_deploy.yml
  build.gradle
  gradlew
  src/main/java/SMU/BAMBOO/Hompage/BambooHompageApplication.java
  src/main/java/SMU/BAMBOO/Hompage/domain/enums/SubjectName.java
  src/main/java/SMU/BAMBOO/Hompage/domain/mainActivites/controller/MainActivitiesController.java
  src/main/java/SMU/BAMBOO/Hompage/domain/mainActivites/dto/MainActivitiesRequestDTO.java
  src/main/java/SMU/BAMBOO/Hompage/domain/mainActivites/dto/MainActivitiesResponseDTO.java
  src/main/java/SMU/BAMBOO/Hompage/domain/mainActivites/entity/MainActivities.java
  src/main/java/SMU/BAMBOO/Hompage/domain/mainActivites/repository/MainActivitiesJpaRepository.java
  src/main/java/SMU/BAMBOO/Hompage/domain/mainActivites/repository/MainActivitiesRepository.java
  src/main/java/SMU/BAMBOO/Hompage/domain/mainActivites/repository/MainActivitiesRepositoryImpl.java
  src/main/java/SMU/BAMBOO/Hompage/domain/mainActivites/service/MainActivitiesService.java
  src/main/java/SMU/BAMBOO/Hompage/domain/mainActivites/service/MainActivitiesServiceImpl.java
  src/main/java/SMU/BAMBOO/Hompage/domain/notice/entity/Notice.java
  src/main/java/SMU/BAMBOO/Hompage/global/config/AwsS3Config.java
  src/main/java/SMU/BAMBOO/Hompage/global/config/SecurityConfig.java
  src/main/java/SMU/BAMBOO/Hompage/global/exception/ErrorCode.java
  src/main/java/SMU/BAMBOO/Hompage/global/upload/AwsS3Service.java
  src/main/resources/application.yml
Labels: feature

#28 Feature/27 tag
  src/main/java/SMU/BAMBOO/Hompage/domain/tag/entity/Tag.java
  src/main/java/SMU/BAMBOO/Hompage/domain/tag/entity/controller/TagController.java
  src/main/java/SMU/BAMBOO/Hompage/domain/tag/entity/dto/TagRequestDTO.java
  src/main/java/SMU/BAMBOO/Hompage/domain/tag/entity/dto/TagResponseDTO.java
  src/main/java/SMU/BAMBOO/Hompage/domain/tag/entity/repository/TagJpaRepository.java
  src/main/java/SMU/BAMBOO/Hompage/domain/tag/entity/repository/TagRepository.java
  src/main/java/SMU/BAMBOO/Hompage/domain/tag/entity/repository/TagRepositoryImpl.java
  src/main/java/SMU/BAMBOO/Hompage/domain/tag/entity/service/TagService.java
  src/main/java/SMU/BAMBOO/Hompage/domain/tag/entity/service/TagServiceImpl.java
Labels: feature

#29 PR FROM [feature/25-library-post] TO [develop]
  src/main/java/SMU/BAMBOO/Hompage/domain/libraryPost/controller/LibraryPostController.java
  src/main/java/SMU/BAMBOO/Hompage/domain/libraryPost/dto/LibraryPostRequestDTO.java
  src/main/java/SMU/BAMBOO/Hompage/domain/libraryPost/dto/LibraryPostResponseDTO.java
  src/main/java/SMU/BAMBOO/Hompage/domain/libraryPost/entity/LibraryPost.java
  src/main/java/SMU/BAMBOO/Hompage/domain/libraryPost/repository/LibraryPostJpaRepository.java
  src/main/java/SMU/BAMBOO/Hompage/domain/libraryPost/repository/LibraryPostRepository.java
  src/main/java/SMU/BAMBOO/Hompage/domain/libraryPost/repository/LibraryPostRepositoryImpl.java
  src/main/java/SMU/BAMBOO/Hompage/domain/libraryPost/service/LibraryPostService.java
  src/main/java/SMU/BAMBOO/Hompage/domain/libraryPost/service/LibraryPostServiceImpl.java
  src/main/java/SMU/BAMBOO/Hompage/domain/mapping/LibraryPostTag.java
  src/main/java/SMU/BAMBOO/Hompage/domain/tag/entity/Tag.java
  src/main/java/SMU/BAMBOO/Hompage/domain/tag/entity/controller/TagController.java
  src/main/java/SMU/BAMBOO/Hompage/domain/tag/entity/dto/TagRequestDTO.java
  src/main/java/SMU/BAMBOO/Hompage/domain/tag/entity/dto/TagResponseDTO.java
  src/main/java/SMU/BAMBOO/Hompage/domain/tag/entity/repository/TagJpaRepository.java
  src/main/java/SMU/BAMBOO/Hompage/domain/tag/entity/repository/TagRepository.java
  src/main/java/SMU/BAMBOO/Hompage/domain/tag/entity/repository/TagRepositoryImpl.java
  src/main/java/SMU/BAMBOO/Hompage/domain/tag/entity/service/TagService.java
  src/main/java/SMU/BAMBOO/Hompage/domain/tag/entity/service/TagServiceImpl.java
  src/main/resources/application.yml
Labels: feature, refactor

#32 마이페이지 기본 정보 불러오기
  src/main/java/SMU/BAMBOO/Hompage/domain/member/controller/MemberController.java
  src/main/java/SMU/BAMBOO/Hompage/domain/member/dto/response/MyPageResponse.java
Labels: feature

#35 Feature/31 my page
  src/main/java/SMU/BAMBOO/Hompage/domain/mainActivites/controller/MainActivitiesController.java
  src/main/java/SMU/BAMBOO/Hompage/domain/member/controller/MemberController.java
  src/main/java/SMU/BAMBOO/Hompage/domain/member/dto/request/ProfileImageRequest.java
  src/main/java/SMU/BAMBOO/Hompage/domain/member/dto/response/MyPageResponse.java
  src/main/java/SMU/BAMBOO/Hompage/domain/member/entity/Member.java
  src/main/java/SMU/BAMBOO/Hompage/domain/member/service/MemberService.java
  src/main/java/SMU/BAMBOO/Hompage/domain/member/service/MemberServiceImpl.java
  src/main/java/SMU/BAMBOO/Hompage/global/exception/ErrorCode.java
  src/main/java/SMU/BAMBOO/Hompage/global/upload/AwsS3Service.java
Labels: feature

#37 ✨ 마이페이지 개인정보 수정
  src/main/java/SMU/BAMBOO/Hompage/domain/member/controller/MemberController.java
  src/main/java/SMU/BAMBOO/Hompage/domain/member/dto/request/ProfileImageRequest.java
  src/main/java/SMU/BAMBOO/Hompage/domain/member/dto/request/UpdateProfileDto.java
  src/main/java/SMU/BAMBOO/Hompage/domain/member/dto/request/UpdatePwDto.java
  src/main/java/SMU/BAMBOO/Hompage/domain/member/entity/Member.java
  src/main/java/SMU/BAMBOO/Hompage/domain/member/service/MemberService.java
  src/main/java/SMU/BAMBOO/Hompage/domain/member/service/MemberServiceImpl.java
Labels: feature

#39 ✨ 회원 권한 수정
  src/main/java/SMU/BAMBOO/Hompage/domain/member/controller/MemberController.java
  src/main/java/SMU/BAMBOO/Hompage/domain/member/dto/request/TestUpdateRoleDto.java
  src/main/java/SMU/BAMBOO/Hompage/domain/member/dto/request/UpdateRoleDto.java
  src/main/java/SMU/BAMBOO/Hompage/domain/member/entity/Member.java
  src/main/java/SMU/BAMBOO/Hompage/domain/member/service/MemberService.java
  src/main/java/SMU/BAMBOO/Hompage/domain/member/service/MemberServiceImpl.java
  src/main/java/SMU/BAMBOO/Hompage/global/exception/ErrorCode.java
Labels: feature

#41 ✨ 회원 리스트 조회
  .gitignore
  build.gradle
  src/main/java/SMU/BAMBOO/Hompage/domain/enums/Role.java
  src/main/java/SMU/BAMBOO/Hompage/domain/member/controller/MemberController.java
  src/main/java/SMU/BAMBOO/Hompage/domain/member/entity/Member.java
  src/main/java/SMU/BAMBOO/Hompage/domain/member/repository/MemberRepository.java
  src/main/java/SMU/BAMBOO/Hompage/domain/member/repository/MemberRepositoryImpl.java
  src/main/java/SMU/BAMBOO/Hompage/domain/member/service/MemberService.java
  src/main/java/SMU/BAMBOO/Hompage/domain/member/service/MemberServiceImpl.java
  src/main/java/SMU/BAMBOO/Hompage/global/config/QueryDSLConfig.java
  src/main/java/SMU/BAMBOO/Hompage/global/mail/config/MailConfig.java
Labels: feature

#45 ♻️ 주요활동 게시판 Member 연결
  src/main/java/SMU/BAMBOO/Hompage/domain/mainActivites/controller/MainActivitiesController.java
  src/main/java/SMU/BAMBOO/Hompage/domain/mainActivites/dto/MainActivitiesRequestDTO.java
  src/main/java/SMU/BAMBOO/Hompage/domain/mainActivites/dto/MainActivitiesResponseDTO.java
  src/main/java/SMU/BAMBOO/Hompage/domain/mainActivites/entity/MainActivities.java
  src/main/java/SMU/BAMBOO/Hompage/domain/mainActivites/repository/MainActivitiesJpaRepository.java
  src/main/java/SMU/BAMBOO/Hompage/domain/mainActivites/repository/MainActivitiesRepository.java
  src/main/java/SMU/BAMBOO/Hompage/domain/mainActivites/repository/MainActivitiesRepositoryImpl.java
  src/main/java/SMU/BAMBOO/Hompage/domain/mainActivites/service/MainActivitiesService.java
  src/main/java/SMU/BAMBOO/Hompage/domain/mainActivites/service/MainActivitiesServiceImpl.java
  src/main/java/SMU/BAMBOO/Hompage/global/config/SecurityConfig.java
  src/main/java/SMU/BAMBOO/Hompage/global/exception/ErrorCode.java
Labels: refactor

#47 ✨ 주요활동 게시판 게시물 조회 기능 구현
  src/main/java/SMU/BAMBOO/Hompage/domain/mainActivites/controller/MainActivitiesController.java
  src/main/java/SMU/BAMBOO/Hompage/domain/mainActivites/dto/MainActivitiesResponseDTO.java
  src/main/java/SMU/BAMBOO/Hompage/domain/mainActivites/service/MainActivitiesService.java
  src/main/java/SMU/BAMBOO/Hompage/domain/mainActivites/service/MainActivitiesServiceImpl.java
Labels: feature

#48 ✨ 과목 CRUD 로직 추가
  src/main/java/SMU/BAMBOO/Hompage/domain/enums/SubjectName.java
  src/main/java/SMU/BAMBOO/Hompage/domain/subject/controller/SubjectController.java
  src/main/java/SMU/BAMBOO/Hompage/domain/subject/dto/SubjectRequestDTO.java
  src/main/java/SMU/BAMBOO/Hompage/domain/subject/dto/SubjectResponseDTO.java
  src/main/java/SMU/BAMBOO/Hompage/domain/subject/entity/Subject.java
  src/main/java/SMU/BAMBOO/Hompage/domain/subject/repository/SubjectJpaRepository.java
  src/main/java/SMU/BAMBOO/Hompage/domain/subject/repository/SubjectRepository.java
  src/main/java/SMU/BAMBOO/Hompage/domain/subject/repository/SubjectRepositoryImpl.java
  src/main/java/SMU/BAMBOO/Hompage/domain/subject/service/SubjectService.java
  src/main/java/SMU/BAMBOO/Hompage/domain/subject/service/SubjectServiceImpl.java
  src/main/java/SMU/BAMBOO/Hompage/global/config/SecurityConfig.java
Labels: feature

#50 🐛 프로필 수정시 기본 이미지로 변경되는 오류
  src/main/java/SMU/BAMBOO/Hompage/domain/member/service/MemberServiceImpl.java
Labels: fix

#51 ✨ 프로필 이미지 삭제 기능 추가
  src/main/java/SMU/BAMBOO/Hompage/domain/member/controller/MemberController.java
  src/main/java/SMU/BAMBOO/Hompage/domain/member/entity/Member.java
  src/main/java/SMU/BAMBOO/Hompage/domain/member/service/MemberService.java
  src/main/java/SMU/BAMBOO/Hompage/domain/member/service/MemberServiceImpl.java
Labels: feature

#55 Feature/54 study
  src/main/java/SMU/BAMBOO/Hompage/domain/mapping/MemberStudy.java
  src/main/java/SMU/BAMBOO/Hompage/domain/member/entity/Member.java
  src/main/java/SMU/BAMBOO/Hompage/domain/member/repository/MemberJpaRepository.java
  src/main/java/SMU/BAMBOO/Hompage/domain/member/repository/MemberRepository.java
  src/main/java/SMU/BAMBOO/Hompage/domain/member/repository/MemberRepositoryImpl.java
  src/main/java/SMU/BAMBOO/Hompage/domain/study/controller/StudyController.java
  src/main/java/SMU/BAMBOO/Hompage/domain/study/dto/StudyRequestDTO.java
  src/main/java/SMU/BAMBOO/Hompage/domain/study/dto/StudyResponseDTO.java
  src/main/java/SMU/BAMBOO/Hompage/domain/study/entity/Study.java
  src/main/java/SMU/BAMBOO/Hompage/domain/study/repository/StudyJpaRepository.java
  src/main/java/SMU/BAMBOO/Hompage/domain/study/repository/StudyRepository.java
  src/main/java/SMU/BAMBOO/Hompage/domain/study/repository/StudyRepositoryImpl.java
  src/main/java/SMU/BAMBOO/Hompage/domain/study/service/StudyService.java
  src/main/java/SMU/BAMBOO/Hompage/domain/study/service/StudyServiceImpl.java
  src/main/java/SMU/BAMBOO/Hompage/global/config/SecurityConfig.java
Labels: feature

#58 ✨ 스터디 정리본 (Inventory) 기능 구현
  src/main/java/SMU/BAMBOO/Hompage/domain/inventory/controller/InventoryController.java
  src/main/java/SMU/BAMBOO/Hompage/domain/inventory/dto/InventoryRequestDTO.java
  src/main/java/SMU/BAMBOO/Hompage/domain/inventory/dto/InventoryResponseDTO.java
  src/main/java/SMU/BAMBOO/Hompage/domain/inventory/entity/Inventory.java
  src/main/java/SMU/BAMBOO/Hompage/domain/inventory/repository/InventoryJpaRepository.java
  src/main/java/SMU/BAMBOO/Hompage/domain/inventory/repository/InventoryRepository.java
  src/main/java/SMU/BAMBOO/Hompage/domain/inventory/repository/InventoryRepositoryImpl.java
  src/main/java/SMU/BAMBOO/Hompage/domain/inventory/service/InventoryService.java
  src/main/java/SMU/BAMBOO/Hompage/domain/inventory/service/InventoryServiceImpl.java
  src/main/java/SMU/BAMBOO/Hompage/global/config/SecurityConfig.java
Labels: feature

#59 🐛 주요활동 게시판 수정 기능 오류 해결
  src/main/java/SMU/BAMBOO/Hompage/domain/mainActivites/controller/MainActivitiesController.java
  src/main/java/SMU/BAMBOO/Hompage/domain/mainActivites/dto/MainActivitiesRequestDTO.java
  src/main/java/SMU/BAMBOO/Hompage/domain/mainActivites/service/MainActivitiesService.java
  src/main/java/SMU/BAMBOO/Hompage/domain/mainActivites/service/MainActivitiesServiceImpl.java
Labels: bug

#62 ✨ 회원 삭제, 탈퇴 구현
  src/main/java/SMU/BAMBOO/Hompage/domain/member/controller/MemberController.java
  src/main/java/SMU/BAMBOO/Hompage/domain/member/entity/Member.java
  src/main/java/SMU/BAMBOO/Hompage/domain/member/repository/MemberRepository.java
  src/main/java/SMU/BAMBOO/Hompage/domain/member/repository/MemberRepositoryImpl.java
  src/main/java/SMU/BAMBOO/Hompage/domain/member/service/MemberService.java
  src/main/java/SMU/BAMBOO/Hompage/domain/member/service/MemberServiceImpl.java
Labels: feature
